USE [master]
GO
/****** Object:  Database [SISTEMA_AUTOBUSES]    Script Date: 19/11/2021 10:57:57 ******/
CREATE DATABASE [SISTEMA_AUTOBUSES]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SISTEMA_AUTOBUSES', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SISTEMA_AUTOBUSES.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SISTEMA_AUTOBUSES_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SISTEMA_AUTOBUSES_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SISTEMA_AUTOBUSES].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET ARITHABORT OFF 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET  ENABLE_BROKER 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET  MULTI_USER 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'SISTEMA_AUTOBUSES', N'ON'
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET QUERY_STORE = OFF
GO
USE [SISTEMA_AUTOBUSES]
GO
/****** Object:  Table [dbo].[AUTOBUSES]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AUTOBUSES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MARCA] [varchar](50) NOT NULL,
	[MODELO] [varchar](50) NOT NULL,
	[PLACA] [varchar](50) NOT NULL,
	[COLOR] [varchar](20) NULL,
	[ANIO] [char](4) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CHOFERES]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHOFERES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[APELLIDO] [varchar](50) NOT NULL,
	[FECHA_NACIMIENTO] [date] NOT NULL,
	[CEDULA] [varchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RUTAS]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RUTAS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[DISTANCIA] [nvarchar](20) NULL,
	[PARADAS] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VIAJES]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VIAJES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_CHOFER] [int] NOT NULL,
	[ID_AUTOBUS] [int] NOT NULL,
	[ID_RUTA] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[AUTOBUSES] ON 
GO
INSERT [dbo].[AUTOBUSES] ([ID], [MARCA], [MODELO], [PLACA], [COLOR], [ANIO]) VALUES (2, N'BMW', N'A-700', N'RD-11111', N'Negro', N'2005')
GO
INSERT [dbo].[AUTOBUSES] ([ID], [MARCA], [MODELO], [PLACA], [COLOR], [ANIO]) VALUES (3, N'Audi', N'B-700', N'RD-22222', N'Gris', N'2005')
GO
INSERT [dbo].[AUTOBUSES] ([ID], [MARCA], [MODELO], [PLACA], [COLOR], [ANIO]) VALUES (9, N'Setra', N'S-100', N'RD-10023', N'Rojo', N'1995')
GO
INSERT [dbo].[AUTOBUSES] ([ID], [MARCA], [MODELO], [PLACA], [COLOR], [ANIO]) VALUES (10, N'Audi', N'P30', N'RD-55555', N'negro', N'1998')
GO
SET IDENTITY_INSERT [dbo].[AUTOBUSES] OFF
GO
SET IDENTITY_INSERT [dbo].[CHOFERES] ON 
GO
INSERT [dbo].[CHOFERES] ([ID], [NOMBRE], [APELLIDO], [FECHA_NACIMIENTO], [CEDULA]) VALUES (2, N'Carlos', N'Hernandez', CAST(N'1997-06-20' AS Date), N'402-4514778-2')
GO
INSERT [dbo].[CHOFERES] ([ID], [NOMBRE], [APELLIDO], [FECHA_NACIMIENTO], [CEDULA]) VALUES (8, N'Francisco', N'Fria', CAST(N'1998-03-13' AS Date), N'010-1234567-2')
GO
INSERT [dbo].[CHOFERES] ([ID], [NOMBRE], [APELLIDO], [FECHA_NACIMIENTO], [CEDULA]) VALUES (9, N'julio', N'garniso', CAST(N'2004-03-12' AS Date), N'00000000000000')
GO
SET IDENTITY_INSERT [dbo].[CHOFERES] OFF
GO
SET IDENTITY_INSERT [dbo].[RUTAS] ON 
GO
INSERT [dbo].[RUTAS] ([ID], [NOMBRE], [DISTANCIA], [PARADAS]) VALUES (1, N'Villa Mella', N'5 KM', 5)
GO
INSERT [dbo].[RUTAS] ([ID], [NOMBRE], [DISTANCIA], [PARADAS]) VALUES (2, N'San Cristobal', N'10 KM', 8)
GO
INSERT [dbo].[RUTAS] ([ID], [NOMBRE], [DISTANCIA], [PARADAS]) VALUES (3, N'Azua', N'25 KM', 6)
GO
INSERT [dbo].[RUTAS] ([ID], [NOMBRE], [DISTANCIA], [PARADAS]) VALUES (5, N'Av. Charles', N'10 KM', 4)
GO
INSERT [dbo].[RUTAS] ([ID], [NOMBRE], [DISTANCIA], [PARADAS]) VALUES (9, N'Av. San Carlos', N'5 KM', 2)
GO
INSERT [dbo].[RUTAS] ([ID], [NOMBRE], [DISTANCIA], [PARADAS]) VALUES (10, N'KM 13 12 11', N'5 KM', 4)
GO
SET IDENTITY_INSERT [dbo].[RUTAS] OFF
GO
SET IDENTITY_INSERT [dbo].[VIAJES] ON 
GO
INSERT [dbo].[VIAJES] ([ID], [ID_CHOFER], [ID_AUTOBUS], [ID_RUTA]) VALUES (13, 9, 10, 10)
GO
SET IDENTITY_INSERT [dbo].[VIAJES] OFF
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__AUTOBUSE__E441AE00E6C7F45D]    Script Date: 19/11/2021 10:57:57 ******/
ALTER TABLE [dbo].[AUTOBUSES] ADD UNIQUE NONCLUSTERED 
(
	[PLACA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__CHOFERES__06BB844878CF04FB]    Script Date: 19/11/2021 10:57:57 ******/
ALTER TABLE [dbo].[CHOFERES] ADD UNIQUE NONCLUSTERED 
(
	[CEDULA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__RUTAS__B21D0AB96E95B354]    Script Date: 19/11/2021 10:57:57 ******/
ALTER TABLE [dbo].[RUTAS] ADD UNIQUE NONCLUSTERED 
(
	[NOMBRE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VIAJES]  WITH CHECK ADD  CONSTRAINT [FK_AUTOBUS_VIAJE] FOREIGN KEY([ID_AUTOBUS])
REFERENCES [dbo].[AUTOBUSES] ([ID])
GO
ALTER TABLE [dbo].[VIAJES] CHECK CONSTRAINT [FK_AUTOBUS_VIAJE]
GO
ALTER TABLE [dbo].[VIAJES]  WITH CHECK ADD  CONSTRAINT [FK_CHOFER_VIAJE] FOREIGN KEY([ID_CHOFER])
REFERENCES [dbo].[CHOFERES] ([ID])
GO
ALTER TABLE [dbo].[VIAJES] CHECK CONSTRAINT [FK_CHOFER_VIAJE]
GO
ALTER TABLE [dbo].[VIAJES]  WITH CHECK ADD  CONSTRAINT [FK_RUTA_VIAJE] FOREIGN KEY([ID_RUTA])
REFERENCES [dbo].[RUTAS] ([ID])
GO
ALTER TABLE [dbo].[VIAJES] CHECK CONSTRAINT [FK_RUTA_VIAJE]
GO
/****** Object:  StoredProcedure [dbo].[SP_BUSCAR_AUTOBUS]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_BUSCAR_AUTOBUS]
@BUSCAR INT
AS
SELECT * FROM AUTOBUSES
WHERE ID LIKE @BUSCAR + '%'

GO
/****** Object:  StoredProcedure [dbo].[SP_BUSCAR_CHOFER]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_BUSCAR_CHOFER]
@BUSCAR INT
AS
SELECT * FROM CHOFERES
WHERE ID LIKE @BUSCAR + '%'
GO
/****** Object:  StoredProcedure [dbo].[SP_BUSCAR_RUTA]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_BUSCAR_RUTA]
@BUSCAR INT
AS
SELECT * FROM RUTAS
WHERE ID LIKE @BUSCAR + '%'
GO
/****** Object:  StoredProcedure [dbo].[SP_BUSCAR_VIAJE]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_BUSCAR_VIAJE]
@BUSCAR INT
AS
SELECT * FROM VIAJES
WHERE ID LIKE @BUSCAR + '%'
GO
/****** Object:  StoredProcedure [dbo].[SP_EDITAR_AUTOBUS]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_EDITAR_AUTOBUS]
@ID INT,
@MARCA VARCHAR(50),
@MODELO VARCHAR(50),
@PLACA VARCHAR(50),
@COLOR VARCHAR(20),
@ANIO CHAR(4)
AS
UPDATE AUTOBUSES SET MARCA = @MARCA, MODELO = @MODELO, PLACA = @PLACA, COLOR = @COLOR, ANIO = @ANIO
WHERE ID = @ID
GO
/****** Object:  StoredProcedure [dbo].[SP_EDITAR_CHOFER]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_EDITAR_CHOFER]
@ID INT,
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR(50),
@FECHA_NACIMIENTO DATE,
@CEDULA NVARCHAR(20)
AS
UPDATE CHOFERES SET NOMBRE = @NOMBRE, APELLIDO = @APELLIDO, FECHA_NACIMIENTO = @FECHA_NACIMIENTO, CEDULA = @CEDULA
WHERE ID = @ID
GO
/****** Object:  StoredProcedure [dbo].[SP_EDITAR_RUTA]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_EDITAR_RUTA]
@ID INT,
@NOMBRE VARCHAR(50),
@DISTANCIA NVARCHAR(20),
@PARADAS INT
AS
UPDATE RUTAS SET NOMBRE = @NOMBRE, DISTANCIA = @DISTANCIA, PARADAS = @PARADAS
WHERE ID = @ID
GO
/****** Object:  StoredProcedure [dbo].[SP_EDITAR_VIAJE]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_EDITAR_VIAJE]
@ID INT,
@ID_CHOFER INT,
@ID_AUTOBUS INT,
@ID_RUTA INT
AS
UPDATE VIAJES SET ID_CHOFER = @ID_CHOFER, ID_AUTOBUS = @ID_AUTOBUS, ID_RUTA = @ID_RUTA
WHERE ID = @ID;
GO
/****** Object:  StoredProcedure [dbo].[SP_ELIMINAR_AUTOBUS]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_ELIMINAR_AUTOBUS]
@ID INT
AS
DELETE FROM AUTOBUSES
WHERE ID = @ID
GO
/****** Object:  StoredProcedure [dbo].[SP_ELIMINAR_CHOFER]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_ELIMINAR_CHOFER]
@ID INT
AS
DELETE FROM CHOFERES
WHERE ID = @ID
GO
/****** Object:  StoredProcedure [dbo].[SP_ELIMINAR_RUTAS]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_ELIMINAR_RUTAS]
@ID INT
AS
DELETE FROM RUTAS
WHERE ID = @ID
GO
/****** Object:  StoredProcedure [dbo].[SP_ELIMINAR_VIAJE]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_ELIMINAR_VIAJE]
@ID INT
AS
DELETE FROM VIAJES
WHERE ID = @ID
GO
/****** Object:  StoredProcedure [dbo].[SP_INSERTAR_AUTOBUS]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_INSERTAR_AUTOBUS]
@MARCA VARCHAR(50),
@MODELO VARCHAR(50),
@PLACA VARCHAR(50),
@COLOR VARCHAR(20),
@ANIO CHAR(4)
AS
INSERT INTO AUTOBUSES VALUES (@MARCA, @MODELO, @PLACA, @COLOR, @ANIO)
GO
/****** Object:  StoredProcedure [dbo].[SP_INSERTAR_CHOFER]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_INSERTAR_CHOFER]
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR(50),
@FECHA_NACIMIENTO DATE,
@CEDULA VARCHAR(20)
AS
INSERT INTO CHOFERES VALUES (@NOMBRE, @APELLIDO, @FECHA_NACIMIENTO, @CEDULA)
GO
/****** Object:  StoredProcedure [dbo].[SP_INSERTAR_RUTA]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_INSERTAR_RUTA]
@NOMBRE VARCHAR(50),
@DISTANCIA NVARCHAR(20),
@PARADAS INT
AS
INSERT INTO RUTAS VALUES (@NOMBRE, @DISTANCIA, @PARADAS)
GO
/****** Object:  StoredProcedure [dbo].[SP_INSERTAR_VIAJE]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_INSERTAR_VIAJE]
@ID_CHOFER INT,
@ID_AUTOBUS INT,
@ID_RUTA INT
AS
INSERT INTO VIAJES VALUES(@ID_CHOFER, @ID_AUTOBUS, @ID_RUTA)
GO
/****** Object:  StoredProcedure [dbo].[SP_LISTAR_AUTOBUSES]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_LISTAR_AUTOBUSES]
AS
SELECT * FROM AUTOBUSES;
GO
/****** Object:  StoredProcedure [dbo].[SP_LISTAR_CHOFER]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_LISTAR_CHOFER]
AS
SELECT * FROM CHOFERES;
GO
/****** Object:  StoredProcedure [dbo].[SP_LISTAR_RUTAS]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_LISTAR_RUTAS]
AS
SELECT * FROM RUTAS;
GO
/****** Object:  StoredProcedure [dbo].[SP_LISTAR_VIAJES]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_LISTAR_VIAJES]
AS
SELECT V.ID, C.ID as ID_C, A.ID as ID_A, R.ID as ID_R,CONCAT(C.NOMBRE, ' ', C.APELLIDO) as 'CHOFER', C.CEDULA as CEDULA, A.MARCA as 'MARCA AUTOBUS', A.MODELO as 'MODELO AUTOBUS', A.PLACA as 'PLACA AUTOBUS', R.NOMBRE as RUTA, R.DISTANCIA as DISTACIA
FROM VIAJES V
INNER JOIN CHOFERES C ON V.ID_CHOFER = C.ID
INNER JOIN AUTOBUSES A ON V.ID_AUTOBUS = A.ID
INNER JOIN RUTAS R ON V.ID_RUTA = R.ID;
GO
/****** Object:  StoredProcedure [dbo].[SP_LST_AUTOBUSES_DISPONIBLES]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_LST_AUTOBUSES_DISPONIBLES]
AS
SELECT DISTINCT ID, CONCAT(MARCA, ' ', MODELO) as 'AUTOBUS', PLACA, COLOR, ANIO 
FROM AUTOBUSES WHERE ID NOT IN ( SELECT ID_AUTOBUS FROM VIAJES);

EXEC SP_LST_AUTOBUSES_DISPONIBLES;
GO
/****** Object:  StoredProcedure [dbo].[SP_LST_CHOFERES_DISPONIBLES]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_LST_CHOFERES_DISPONIBLES]
AS
SELECT DISTINCT ID, CONCAT(NOMBRE, ' ', APELLIDO) as 'NOMBRE COMPLETO', FECHA_NACIMIENTO, CEDULA 
FROM CHOFERES WHERE ID NOT IN ( SELECT ID_CHOFER FROM VIAJES);


EXEC SP_LST_CHOFERES_DISPONIBLES;
GO
/****** Object:  StoredProcedure [dbo].[SP_LST_RUTAS_DISPONIBLES]    Script Date: 19/11/2021 10:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_LST_RUTAS_DISPONIBLES]
AS
SELECT DISTINCT ID, CONCAT(NOMBRE, ' ', DISTANCIA) as 'RUTA', PARADAS
FROM RUTAS WHERE ID NOT IN ( SELECT ID_RUTA FROM VIAJES);
GO
USE [master]
GO
ALTER DATABASE [SISTEMA_AUTOBUSES] SET  READ_WRITE 
GO
